name: gewichts_app
description: Volvo Gewichts App
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"   # wichtig wegen Record-Typen ( (double a, double b) )

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
