name: Deploy Flutter Web to GitHub Pages
on:
  push: { branches: [ main ] }
  workflow_dispatch: {}
these   rules name.: The gew recommended name isichts_app_flutter
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main (full)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Show repo & pubspec header (with invisible chars)
        run: |
          pwd
          ls -la
          echo "---- pubspec.yaml head ----"
          head -n 5 pubspec.yaml || true
          echo "---- pubspec name line (raw) ----"
          sed -n '1p' pubspec.yaml | cat -A
          echo "---- grep name ----"
          grep -n '^name:' pubspec.yaml || true

      - name: Force valid package name in pubspec (CI only)
        run: |
          perl -0777 -pe 's/^\s*name\s*:\s*"?[a-zA-Z0-9_-]+"?/name: gewichts_app_flutter/sm' pubspec.yaml > pubspec.yaml.fixed
          tr -d '\r' < pubspec.yaml.fixed > pubspec.yaml
          rm -f pubspec.yaml.fixed
          echo "---- pubspec after fix (first 3 lines) ----"
          head -n 3 pubspec.yaml | cat -A

      - name: Ensure lib/main.dart exists
        run: |
          test -f lib/main.dart && echo "OK: lib/main.dart" || (echo "MISSING: lib/main.dart"; exit 1)

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Enable web & get packages
  run: |
    flutter config --enable-web
    flutter pub get
    flutter doctor -v

      - name: Build web (release)
        run: flutter build web --release --base-href=/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
